### PR TITLE
Replace poison with the faster jason lib

### PR DESCRIPTION
**Pull request by LostKobrakai**
Jason is a faster json lib similar to poison, so it's been a drop in replacement. In my crude tests it shaved of about half a second in compile time for the cldr testsuite (4.4s -> 3.9), which is not really much, but if it's there why not use it. It might just be that we need to wait for the full release, because it's currently just a rc version.

For more details: https://elixirforum.com/t/announcing-jason-a-blazing-fast-json-parser-and-generator-in-pure-elixir/11030

P.S: I've done a `mix deps.clean --unlock`, which removed way more than poison from the lockfile. That might not be what you wanted.

### CODE REVIEW

**Comment by kipcole9** [comment]
Not surprisingly I get the same performance improvement on my dev machine.

I've been thinking that having the json lib be configurable might be the way to go since

1. there's a risk that an app ends up with multiple json decoders configured which isn't very helpful and
2. who knows when another faster one becomes available, including `jason_native` which is planned

The default probably would continue to be `Poison` until its clear that the community has shifted to `Jason` and then the default can switch.

Thoughts?

**Comment by LostKobrakai** [comment]
Your first point is certainly the only one I see for adding a configurable json decoder. I mean those packages will need to have the same/similar functional interface anyways and it's not like those pop up each and every week.

**Comment by Schultzer** [comment]
@LostKobrakai Not really a simply `Kernel.apply/3` would solve that.
The only thing that would be surprising is if the `decoding` returned a Keyword list  instead of a map but that wouldn't be a bad thing perse 

I'll agree on Kip's thought about making decoding configurable, and as long as Phoenix ships with poison I don't see any point in change this.

**Comment by kipcole9** [comment]
I've pushed an update as ex_cldr 1.10 that includes configuring the json library.  The lib will need to be configured in the client app.  Hex doesn't allow publishing with a pre-release dependency so for now `jason` is not included in ex_cldr's `mix.exs` configuration.  

Thanks much for the PR.

**Pull request closed without merging**
