### PR TITLE
Docs improvements by grouping modules

### PR DESCRIPTION
**Pull request by LostKobrakai**
I just wanted to create the PRs while I have some free time. Will update it to use ex_doc v0.17 as soon as it's released. I kind of guessed the helper modules by the module docs present by now. Maybe there are more modules you think might be nice to be visually grouped in the documentation as well.

### CODE REVIEW

**Comment by kipcole9** [comment]
Much appreciated. Am just coming to the end of a new piece of work that implements a formal language-tag parser which is now used as the foundation of a locale in cldr and friends.  I've added an `accept-language` header parser too. This will let me finish up the Plug thats long been on pause.

I'm starting to focus now on documentation and module structure and in particular to be a lot clearer about the public API.

This PR helps remind me that I can definitely improve the module organisation and probably revisit a few names as well.

**Comment by LostKobrakai** [comment]
That sounds nice. With my additions to the upcoming ex_doc version you don't necessarily need to rename modules, but you can just group arbitrary modules by their names or some regex matching the names.

**Comment by kipcole9** [comment]
Its a welcome update to `ex_doc` and I look forward to it.  But as you point out, some of the grouping isn't obvious. Which suggests I should review critically before lining up for a 1.0 release in a couple of months.

**Comment by LostKobrakai** [comment]
0.17 is now released so this and the related PR in the money repo could be merged.

**Pull request merged**
