### PR TITLE
Fix issue where creating the locale folders in _build when compiling …

### LINKED ISSUE #19: Issue compiling on windows
`Cldr.Install.ensure_client_dirs_exist!` does try to create the following directories on windows:

```
Generating Cldr for 10 locales ["de", "de-AT", "de-BE", "de-CH", "de-IT", ...] with default locale "en"
["/c:", "/Users", "/fklement", "/Desktop", "/connect", "/_build", "/dev",
 "/lib", "/ex_cldr", "/priv", "/cldr", "/locales"]
```

For the following correct path:  `c:/Users/fklement/Desktop/connect/…`

Noticed by @fklement

### PR DESCRIPTION
**Pull request by LostKobrakai**
…does fail on windows.

Does fix #19

### CODE REVIEW

**Comment by kipcole9** [comment]
Thanks for the catch.  I need to build a windows test environment.  I'm on the road for the next several days so I won't be able to merge until I get back online.

**Comment by kipcole9** [comment]
Since `File.mkdir/1` doesn't create parent directories I don't think I can accept this PR as is.  I'm back from vacation so will sort this out this week.

**Comment by LostKobrakai** [comment]
It's mkdir_p/1 which  does that, otherwise is wouldn't work on the system my coworker had noticed the issue on.

-- 
www.kobrakai.de | Bauernstraße 5B | 86508 Rehling | 015221616149

**Comment by kipcole9** [comment]
Arrrgggghhh.  Got it.  Will merge and update on hex in the next 24 hours.

**Pull request merged**
