### PR TITLE
Add Cldr.Language.Backend

### PR DESCRIPTION
**Pull request by Schultzer**

### CODE REVIEW

**Comment by kipcole9** [comment]
Thanks @Schultzer, apologies for not including this already and for the abrupt change in strategy here.

**Comment by LostKobrakai** [comment]
I seems to have missed something. Why do we need to have dependants in the core package?

**Comment by kipcole9** [comment]
Because `use Cldr` will invoke the `__using__/2` macro in `Cldr` (of course).  From that point code needs to be generated into the backend.  So the `__using__/2` macros needs to know who is going to generate that code.  I'm not aware of a mechanism whereby the dependent packages can otherwise be notified that its time to generate code for a given backend.

The original discovery mechanism had a fatal flaw (it used `Mix.Project.in_dependency/2` which does a `cd` which messes up everything in a parallel compiler environment.  I will revisit this to find a better way.  But as you pointed out in a forum post, this nearly always ends unhappily.

So for now at least, the potential backends a registered in `Cldr` so `Cldr` knows to call them when compiling a backend.

**Comment by LostKobrakai** [comment]
I'll have to give that some more though, but I don't feel like needing to know all possible dependencies is a great solution.

**Comment by kipcole9** [comment]
Definitely not great at all. In fact horrible.  But I had to revert my original discovery mechanism.  Because basically it didn’t work.  Its a project for this weekend.

I was quite happy with the strategy of defining a `cldr_provider` MFA in mix.exs of a project and then introspecting the project.  But most of the interesting parts of Mix for that are not public API.  And although this is a purely compile time thing perhaps its better to go with a protocol.  Thoughts most welcome.

**Comment by LostKobrakai** [comment]
Why not something like `use Cldr, provider: [:cldr_date_times, :cldr_languages]`

**Comment by kipcole9** [comment]
Its an option.  Maybe even a good option.  I feel like its one more thing to forget that shouldn't need to be a concern to a developer. But then maybe thats useful configuration if different backends have different purposes?

**Comment by LostKobrakai** [comment]
It just needs to be properly documented and errors should hint about it, but those just are separate dependencies and I really prefer manual wireing over some automatic wireing I cannot control.

**Comment by kipcole9** [comment]
Good reasoning as usual.  I'll do better at collaborating in advance when I get `ex_cldr_dates_times` up to version 2.0 and park it all in a new Github organization. I accept your suggestion for configuring providers and will get that sorted out for a 2.1 release over the weekend.

**Comment by kipcole9** [comment]
As of [this commit](https://github.com/kipcole9/cldr/commit/ddab960b5ad7d5ea4dcfbd71fcccf4d77d0b086b) the `:providers` are configured on the `use Cldr` in the backend.  Your views would be appreciated especially on the current strategy of attempting to configure 'known' backends if none are specified.  

Since configuring no providers is perfectly legitimate this might not be the right strategy.  But for anyone coming from Cldr 1.8 there is an expectation that installed packages will be configured.  I do put a console warning if none are configured.

This will bump ex_cldr to version 2.1 and since there is a new `:providers` key in the `Cldr.Config` struct, the other packages will go to 2.1 as well. So I want to be a little more cautious before publishing.

**Comment by LostKobrakai** [comment]
Maybe you can check for providers not being supplied (nil) vs empty list ([]) for the warning. Other than that I like it. Maybe you could reuse the same function for applying the providers though. Currently you seem to duplicate that work.

**Pull request merged**
