### PR TITLE
fix add_measurement_system/1 and restrict underscore/1 from underscor…

### PR DESCRIPTION
**Pull request by Schultzer**
Fix `add_measurement_system/1` and restrict `underscore/1` from underscoring `territory_codes`

this will correct the results in `territory_info/0` where it before defaulted to `:"001"` because of `underscore/1` lowercased the territory codes.

### CODE REVIEW

**Comment by kipcole9** [comment]
Thanks for the PR, much appreciated.  The PR message mentioned `Cldr.Config.territory_info/1` but I didn't see the code?  It makes sense so I will add it in anyway.

I'm a little concerned about special casing the territory codes in `Cldr.String.underscore` though since they can change with each data release (CLDR 32 was released today, for example).

Can you help me understand the bug a bit better?  On master I get the following, where the territory code is definitely an uncased atom.  In general I'm trying to promote standardisation of:

* territory codes are upcased atoms
* currency codes are uncased atoms
* language codes are strings (properly formatted, but using case-independent comparison)

```elixir
iex(2)> Cldr.Config.territory_info[:GB]
%{
  currency: %{GBP: %{from: ~D[1694-07-27]}},
  gdp: 2788000000000,
  language_population: %{
    "bn" => %{population_percent: 0.67},
    "cy" => %{official_status: "official_regional", population_percent: 0.77},
    "de" => %{population_percent: 6},
    "el" => %{population_percent: 0.34},
    "en" => %{official_status: "official", population_percent: 99},
    "fr" => %{population_percent: 19},
    "ga" => %{official_status: "official_regional", population_percent: 0.026},
    "gd" => %{
      official_status: "official_regional",
      population_percent: 0.099,
      writing_percent: 5
    },
    "it" => %{population_percent: 0.34},
    "ks" => %{population_percent: 0.19},
    "kw" => %{population_percent: 0.0031},
    "ml" => %{population_percent: 0.035},
    "pa" => %{population_percent: 0.79},
    "sco" => %{population_percent: 2.7, writing_percent: 5},
    "syl" => %{population_percent: 0.51},
    "yi" => %{population_percent: 0.049},
    "zh-Hant" => %{population_percent: 0.54}
  },
  literacy_percent: 99,
  measurement_system: "metric",
  paper_size: "A4",
  population: 64430400,
  telephone_country_code: 44,
  temperature_measurement: "metric"
}
```

**Comment by Schultzer** [comment]
Sorry for my communication skills. 

I'll try to clarify whats going on.

1. All territory codes are [ISO_3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) as you probably already know.
2. The problem is in `add_measurement_system/1` it calls  `underscore/1` lowercase all strings
so when `add_measurement_system/1` tries to map a given territory there is an uppercased [ISO_3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) atom, it fails because `underscore/1` have lowercased it.

another solution to this problem would be to have a function there validates [ISO_3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) so that it doesn't care about it being a string, atom, uppercased or lowercased.

so if you take a look in in [measurementData.json](https://github.com/unicode-cldr/cldr-core/blob/c48314ac492abd6498875eed9e68524e92684bf2/supplemental/measurementData.json) you'll notice that for `Cldr.Config.territory_info[:GB]` the `measurement_system:` should be `"UK"` instead of `"metric"`

you can also test this with `Cldr.Config.territory_info[:US]` where it results in `"metric"` too

I hope this clarified the issue, I'll admit that this can be should in a smarter way. let me know in which way you see this issue solved. 😄

**Comment by kipcole9** [comment]
Ah, ok, got it.  Thanks much.  Will dive into this today.  Have updated master branch to CLDR version 32 which came out today and adds new data.  Very smooth transition from a code point of view so confidence is increasing that the underlying data transformation part of ex_cldr is reasonably solid.

Supporting what you need from a territories point of view and some additional documentation updates is basically all I plan on before declaring a 1.0 release so please do keep the comments and suggestions coming.

**Comment by kipcole9** [comment]
Also just want to note that there are more territories that just ISO_3166-2 since CLDR  really uses https://en.wikipedia.org/wiki/UN_M.49

**Comment by Schultzer** [comment]
Your right, again my bad when I said territory codes I really meant country code.

**Comment by kipcole9** [comment]
OK, fixed that bug, updated to CLDR 32 and added:

1. `Cldr.known_territories/0`
2. `Cldr.validate_territory/1`
3. `Cldr.Config.territory_info/1`

Released on [hex as version 0.10.0](https://hex.pm/packages/ex_cldr)

**Pull request closed without merging**
